# Generated by Django 2.2.7 on 2019-11-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze_tweets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='keyword',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='polarity',
            field=models.DecimalField(decimal_places=5, max_digits=6, null=True),
        ),
        migrations.AddIndex(
            model_name='tweet',
            index=models.Index(fields=['keyword'], name='analyze_twe_keyword_b025be_idx'),
        ),
    ]
