# Generated by Django 2.2.7 on 2019-11-18 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyze_tweets', '0002_auto_20191116_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='tweet',
            name='analyze_twe_keyword_b025be_idx',
        ),
        migrations.AlterField(
            model_name='job',
            name='keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyze_tweets.Keyword'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyze_tweets.Keyword'),
        ),
        migrations.AddIndex(
            model_name='tweet',
            index=models.Index(fields=['keyword'], name='analyze_twe_keyword_af9768_idx'),
        ),
    ]
