# Generated by Django 2.2.7 on 2020-02-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze_tweets', '0003_auto_20191118_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='keyword',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
