# Generated by Django 2.2.7 on 2020-02-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze_tweets', '0003_auto_20191118_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='completion_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
