# Generated by Django 2.2.7 on 2020-02-11 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyze_tweets', '0004_auto_20200205_1731'),
        ('analyze_tweets', '0005_auto_20200208_1620'),
    ]

    operations = [
    ]
