# Generated by Django 2.2.7 on 2020-02-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze_tweets', '0005_auto_20200208_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('RUNNING', 'RUNNING'), ('COMPLETED', 'COMPLETED')], default='PENDING', max_length=255),
        ),

        migrations.RemoveField(
            model_name='job',
            name= 'completion_status',
            field=models.BooleanField(default=False),
        ),
    ]