# Generated by Django 2.2.7 on 2020-02-17 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyze_tweets', '0006_merge_20200211_1740'),
        ('analyze_tweets', '0007_auto_20200213_1343'),
    ]

    operations = [
    ]
